### ISSUE TITLE
protocol docs do not match the uuids

### ISSUE THREAD

**Issue by AlexDM0** [crownstone/bluenet#22]
The general service in the docs is 
f5f90000-f5f9-11e4-aa15-123b93f75cba
f5f90000-59f9-11e4-aa15-123b93f75cba  <-- actual value

Same for the characteristics. Please double check the docs

**Comment by mrquincle** [comment]
The General service can now be found at 24f20000-7d10-4805-bfc1-7663a01c3bff.

The updated doc can be found at:
https://github.com/crownstone/bluenet/blob/master/docs/PROTOCOL.md
