### ISSUE TITLE
Error state reset does not update the event bitmask

### ISSUE THREAD

**Issue by AlexDM0** [crownstone/bluenet#50]
This command: https://github.com/crownstone/bluenet/blob/master/src/processing/cs_CommandHandler.cpp#L572

does not update the bitmask in the advertisement: 
https://github.com/crownstone/bluenet/blob/master/src/ble/cs_ServiceData.cpp#L259

This makes it impossible to clear an error completely.

**Comment by vliedel** [comment]
Has been fixed.
