### ISSUE TITLE
Channel switch problem ADC

### ISSUE THREAD

**Issue by mrquincle** [crownstone/bluenet#53]
It seems Nordic has discovered how to solve the offset mismatch in for SAADC when making use of EasyDMA.

https://devzone.nordicsemi.com/question/119588/offset-in-saadc-samples-with-easy-dma-and-ble/

**Comment by vliedel** [comment]
This was fixed, solution is documented here: https://github.com/crownstone/bluenet/blob/6ad42e77e06d675ff63fdff8f8fab2484d656ea1/docs/ADC.md
